"""EDGAR ingestion.

SEC full-text access is free but rate-limited and requires a declared
User-Agent with contact info. Violating either gets your IP blocked, so this
client is deliberately polite: 10 req/sec ceiling, backoff on 429, and local
caching so re-running ingest never re-downloads.

Set SEC_USER_AGENT in .env before running, e.g.
    SEC_USER_AGENT="finrag research your.email@example.com"
"""

from __future__ import annotations

import json
import re
import time
from dataclasses import dataclass
from pathlib import Path

from finrag.config import DATA_DIR, settings

SEC_BASE = "https://www.sec.gov"
SUBMISSIONS_URL = "https://data.sec.gov/submissions/CIK{cik:010d}.json"
TICKER_MAP_URL = "https://www.sec.gov/files/company_tickers.json"

_MIN_INTERVAL = 0.11  # ~9 req/sec, under the published 10/sec limit
_last_request = 0.0


@dataclass
class FilingRef:
    ticker: str
    cik: int
    form_type: str
    fiscal_year: int
    accession: str
    primary_doc: str

    @property
    def url(self) -> str:
        acc = self.accession.replace("-", "")
        return f"{SEC_BASE}/Archives/edgar/data/{self.cik}/{acc}/{self.primary_doc}"

    @property
    def cache_path(self) -> Path:
        return DATA_DIR / "raw" / f"{self.ticker}_{self.fiscal_year}_{self.form_type}.txt"


def _throttle() -> None:
    global _last_request
    elapsed = time.time() - _last_request
    if elapsed < _MIN_INTERVAL:
        time.sleep(_MIN_INTERVAL - elapsed)
    _last_request = time.time()


def _get(url: str, retries: int = 3) -> str:
    import httpx

    headers = {"User-Agent": settings.user_agent, "Accept-Encoding": "gzip, deflate"}
    for attempt in range(retries):
        _throttle()
        response = httpx.get(url, headers=headers, timeout=30.0, follow_redirects=True)
        if response.status_code == 429:
            time.sleep(2**attempt)
            continue
        response.raise_for_status()
        return response.text
    raise RuntimeError(f"Rate limited after {retries} attempts: {url}")


def resolve_cik(ticker: str) -> int:
    cache = DATA_DIR / "ticker_cik.json"
    if not cache.exists():
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_text(_get(TICKER_MAP_URL))
    mapping = json.loads(cache.read_text())
    for entry in mapping.values():
        if entry["ticker"].upper() == ticker.upper():
            return int(entry["cik_str"])
    raise ValueError(f"Ticker not found in SEC mapping: {ticker}")


def list_filings(ticker: str, form_type: str = "10-K", limit: int = 3) -> list[FilingRef]:
    cik = resolve_cik(ticker)
    data = json.loads(_get(SUBMISSIONS_URL.format(cik=cik)))
    recent = data["filings"]["recent"]

    refs: list[FilingRef] = []
    for i, form in enumerate(recent["form"]):
        if form != form_type:
            continue
        report_date = recent["reportDate"][i]
        refs.append(
            FilingRef(
                ticker=ticker.upper(),
                cik=cik,
                form_type=form_type,
                fiscal_year=int(report_date[:4]),
                accession=recent["accessionNumber"][i],
                primary_doc=recent["primaryDocument"][i],
            )
        )
        if len(refs) >= limit:
            break
    return refs


def html_to_text(html: str) -> str:
    """Strip filing HTML to text while preserving paragraph structure.

    Filing HTML is table-heavy and generated by a dozen different vendors. The
    goal is not fidelity, it is retrievable prose with Item headings intact on
    their own lines so the section splitter can find them.
    """
    from bs4 import BeautifulSoup

    soup = BeautifulSoup(html, "lxml")
    for tag in soup(["script", "style"]):
        tag.decompose()

    text = soup.get_text("\n")
    text = re.sub(r"\xa0", " ", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n\s*\n\s*\n+", "\n\n", text)
    return text.strip()


def fetch_filing(ref: FilingRef, force: bool = False) -> str:
    if ref.cache_path.exists() and not force:
        return ref.cache_path.read_text(encoding="utf-8")
    text = html_to_text(_get(ref.url))
    ref.cache_path.parent.mkdir(parents=True, exist_ok=True)
    ref.cache_path.write_text(text, encoding="utf-8")
    return text
